apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: marketplace-pipeline
spec:
resources:
  - name: git-input
    type: git
  - name: image-output
    type: image
  tasks:
  - name: build-and-push
    taskRef:
      name: build-and-push
    params:
      - name: TLSVERIFY
        value: "false"
    resources:
      inputs:
      - name: source
        resource: git-input
      outputs:
      - name: image
        resource: image-output
  - name: deploy
    taskRef:
      name: openshift-client
    runAfter:
      - build-and-push
    params:
    - name: ARGS
      value:
        - rollout
        - latest
        - quay.io/cbanavik/test:latest 